apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: ${DOMAIN}.viralhelp.ch
spec:
  host: ${DOMAIN}.viralhelp.ch
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: viralhelp-website
  wildcardPolicy: None
